version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"     # S3 API
      - "9003:9001"     # MinIO UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data

  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    depends_on:
      - rabbitmq
      - minio


  ################
  postgres:
    image: postgres:15
    container_name: tb_postgres
    environment:
      POSTGRES_USER: tb_user
      POSTGRES_PASSWORD: tb_pass
      POSTGRES_DB: thingsboard
    volumes:
      - tb_postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  thingsboard:
    image: thingsboard/tb-postgres:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: tb_user
      SPRING_DATASOURCE_PASSWORD: tb_pass
    depends_on:
      - postgres
    ports:
      - "8080:9090"
      - "1883:1883"
    
##############
volumes:
  rabbitmq_data:
  minio_data:
  nodered_data:
  tb_postgres_data:
  # tb_postgres_data: #######